#/*============================================================================
#
#  MYPROJECT: A software package for whatever.
#
#  Copyright (c) University College London (UCL). All rights reserved.
#
#  This software is distributed WITHOUT ANY WARRANTY; without even
#  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
#  PURPOSE.
#
#  See LICENSE.txt in the top level directory for details.
#
#============================================================================*/

version: "{build}"

os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\CMakeHelloWorld

shallow_clone: true

environment:
  matrix:
    - COMPILER: "Visual Studio 12 Win64"

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

before_build:
  - echo --------------------------------------------------------------------------------
  - echo Appveyor environment info:
  - echo COMPILER = %COMPILER%, CONFIGURATION = %CONFIGURATION%
  - cmake -version
  - pwd
  - rem --------------------------------------------------------------------------------

build_script:
  - echo --------------------------------------------------------------------------------
  - echo Build CMakeHelloWorld:
  - mkdir build
  - cd build
  - cmake -G "%COMPILER%" -DCMAKE_PREFIX_PATH=C:\Qt\5.6\msvc2015_64 --config %CONFIGURATION% ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - pwd
  - ctest -C %CONFIGURATION%
